In [1]:
import pandas as pd

In [2]:
csv = ' https://cocl.us/datascience_survey_data'
df = pd.read_csv('https://s3.us.cloud-object-storage.appdomain.cloud/cf-courses-data/CognitiveClass/DP0701EN/version-2/Data-Collisions.csv')

/Users/chunghimlau/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3057: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [9]:
df.shape

(194673, 38)

In [3]:
df.head()

,SEVERITYCODE,X,Y,OBJECTID,INCKEY,COLDETKEY,REPORTNO,STATUS,ADDRTYPE,INTKEY,...,ROADCOND,LIGHTCOND,PEDROWNOTGRNT,SDOTCOLNUM,SPEEDING,ST_COLCODE,ST_COLDESC,SEGLANEKEY,CROSSWALKKEY,HITPARKEDCAR
0,2,-122.323148,47.703140,1,1307,1307,3502005,Matched,Intersection,37475.0,...,Wet,Daylight,NaN,NaN,NaN,10,Entering at angle,0,0,N
1,1,-122.347294,47.647172,2,52200,52200,2607959,Matched,Block,NaN,...,Wet,Dark - Street Lights On,NaN,6354039.0,NaN,11,From same direction - both going straight - bo...,0,0,N
2,1,-122.334540,47.607871,3,26700,26700,1482393,Matched,Block,NaN,...,Dry,Daylight,NaN,4323031.0,NaN,32,One parked--one moving,0,0,N
3,1,-122.334803,47.604803,4,1144,1144,3503937,Matched,Block,NaN,...,Dry,Daylight,NaN,NaN,NaN,23,From same direction - all others,0,0,N
4,2,-122.306426,47.545739,5,17700,17700,1807429,Matched,Intersection,34387.0,...,Wet,Daylight,NaN,4028032.0,NaN,10,Entering at angle,0,0,N

In [10]:
df_1 = df[['SEVERITYCODE','WEATHER','ROADCOND','LIGHTCOND','PEDCYLCOUNT','UNDERINFL']]

,SEVERITYCODE,WEATHER,ROADCOND,LIGHTCOND,PEDCYLCOUNT,UNDERINFL
0,2,Overcast,Wet,Daylight,0,N
1,1,Raining,Wet,Dark - Street Lights On,0,0
2,1,Overcast,Dry,Daylight,0,0
3,1,Clear,Dry,Daylight,0,N
4,2,Raining,Wet,Daylight,0,0
5,1,Clear,Dry,Daylight,0,N
6,1,Raining,Wet,Daylight,0,0
7,2,Clear,Dry,Daylight,1,N
8,1,Clear,Dry,Daylight,0,0
9,2,Clear,Dry,Daylight,0,0
10,1,Overcast,Dry,Daylight,0,0
11,1,Clear,Dry,Daylight,0,0
12,1,Raining,Wet,Dark - Street Lights On,0,0
13,1,Raining,Wet,Dark - No Street Lights,0,0
14,2,Clear,Dry,Dark - Street Lights On,0,N
15,1,NaN,NaN,NaN,0,NaN
16,2,Overcast,Dry,Daylight,0,0
17,1,Overcast,Dry,Daylight,0,0
18,2,Clear,Dry,Daylight,0,N
19,1,Unknown,Dry,Unknown,0,0
20,2,Clear,Dry,Dark - Street Lights On,0,N
21,2,Clear,Dry,Daylight,0,N
22,1,Clear,Dry,Dark - Street Lights On,0,0
23,1,Unknown,Unknown,Unknown,0,0
24,2,Clear,Dry,Daylight,0,N
25,2,Clear,Dry,Daylight,1,N
26,1,Overcast,Wet,Unknown,0,N
27,1,Clear,Dry,Daylight,0,0
28,1,Clear,Dry,Daylight,0,N
29,1,Clear,Dry,Daylight,0,0
...,...,...,...,...,...,...
194643,1,Clear,Dry,Dark - Street Lights On,0,N
194644,1,Clear,Dry,Dusk,0,N
194645,2,Clear,Dry,Dark - Street Lights On,0,N
194646,1,NaN,NaN,NaN,0,NaN
194647,2,Raining,Wet,Dusk,0,N
194648,1,Raining,Wet,Dark - Street Lights On,0,Y
194649,2,Clear,Dry,Dark - Street Lights On,0,N
194650,2,Clear,Dry,Daylight,0,N
194651,1,Clear,Wet,Dark - Street Lights On,0,N
194652,1,Overcast,Wet,Dusk,0,N
194653,2,Overcast,Wet,Dark - Street Lights On,0,Y
194654,1,NaN,NaN,NaN,0,NaN
194655,2,NaN,NaN,NaN,0,NaN
194656,2,Clear,Dry,Daylight,0,N
194657,1,Raining,Wet,Dark - Street Lights On,0,N
194658,1,Raining,Wet,Dark - Street Lights On,0,N
194659,1,Raining,Wet,Dark - Street Lights On,0,N
194660,2,Raining,Wet,Other,0,N
194661,2,Clear,Dry,Daylight,0,Y
194662,1,Clear,Dry,Dusk,0,N
194663,2,Raining,Wet,Daylight,0,N
194664,1,Clear,Dry,Daylight,0,N
194665,1,Clear,Dry,Daylight,0,N
194666,2,Clear,Wet,Daylight,0,N
194667,1,Raining,Wet,Dark - Street Lights On,0,Y
194668,2,Clear,Dry,Daylight,0,N
194669,1,Raining,Wet,Daylight,0,N
194670,2,Clear,Dry,Daylight,0,N
194671,2,Clear,Dry,Dusk,1,N
194672,1,Clear,Wet,Daylight,0,N

In [13]:
# Drop all columns with no predictive value for the context of this project
#df_1 = df[['SEVERITYCODE','WEATHER','ROADCOND','LIGHTCOND','PEDCYLCOUNT','UNDERINFL']]


df_1 = df.drop(columns = ['OBJECTID', 'SEVERITYCODE.1', 'REPORTNO', 'INCKEY', 'COLDETKEY', 
              'X', 'Y', 'STATUS','ADDRTYPE',
              'INTKEY', 'LOCATION', 'EXCEPTRSNCODE',
              'EXCEPTRSNDESC', 'SEVERITYDESC', 'INCDATE',
              'INCDTTM', 'JUNCTIONTYPE', 'SDOT_COLCODE',
              'SDOT_COLDESC', 'PEDROWNOTGRNT', 'SDOTCOLNUM',
              'ST_COLCODE', 'ST_COLDESC', 'SEGLANEKEY',
              'CROSSWALKKEY', 'HITPARKEDCAR', 'PEDCOUNT', 
              'PERSONCOUNT', 'VEHCOUNT', 'COLLISIONTYPE',
              'SPEEDING', 'INATTENTIONIND'])

# Label Encoding
# Convert column to category
df_1["WEATHER"] = df_1["WEATHER"].astype('category')
df_1["ROADCOND"] = df_1["ROADCOND"].astype('category')
df_1["LIGHTCOND"] = df_1["LIGHTCOND"].astype('category')

# Assign variable to new column for analysis
df_1["WEATHER_CODE"] = df_1["WEATHER"].cat.codes
df_1["ROADCOND_CODE"] = df_1["ROADCOND"].cat.codes
df_1["LIGHTCOND_CODE"] = df_1["LIGHTCOND"].cat.codes

df_1.head(5)

,SEVERITYCODE,PEDCYLCOUNT,UNDERINFL,WEATHER,ROADCOND,LIGHTCOND,WEATHER_CODE,ROADCOND_CODE,LIGHTCOND_CODE
0,2,0,N,Overcast,Wet,Daylight,4,8,5
1,1,0,0,Raining,Wet,Dark - Street Lights On,6,8,2
2,1,0,0,Overcast,Dry,Daylight,4,0,5
3,1,0,N,Clear,Dry,Daylight,1,0,5
4,2,0,0,Raining,Wet,Daylight,6,8,5

In [14]:
#Showing the unique value counts of the SEVERITY CODE
df_1['SEVERITYCODE'].value_counts()

1    136485
2     58188
Name: SEVERITYCODE, dtype: int64

In [15]:
#Showing the unique value counts of the WEATHER
df_1['WEATHER'].value_counts()

Clear                       111135
Raining                      33145
Overcast                     27714
Unknown                      15091
Snowing                        907
Other                          832
Fog/Smog/Smoke                 569
Sleet/Hail/Freezing Rain       113
Blowing Sand/Dirt               56
Severe Crosswind                25
Partly Cloudy                    5
Name: WEATHER, dtype: int64

In [17]:
#Showing the unique value counts of the ROAD CONDITION
df_1['ROADCOND'].value_counts()

Dry               124510
Wet                47474
Unknown            15078
Ice                 1209
Snow/Slush          1004
Other                132
Standing Water       115
Sand/Mud/Dirt         75
Oil                   64
Name: ROADCOND, dtype: int64

In [18]:
#Showing the unique value counts of the LIGHT CONDITION
df_1['LIGHTCOND'].value_counts()

Daylight                    116137
Dark - Street Lights On      48507
Unknown                      13473
Dusk                          5902
Dawn                          2502
Dark - No Street Lights       1537
Dark - Street Lights Off      1199
Other                          235
Dark - Unknown Lighting         11
Name: LIGHTCOND, dtype: int64

In [21]:
from sklearn.utils import resample
# Splitting majority and minority classes
df_1_majority = df_1[df_1.SEVERITYCODE==1]
df_1_minority = df_1[df_1.SEVERITYCODE==2]

#Turning majority class to Downsample majority class
df_1_majority_downsampled = resample(df_1_majority,
                                        replace=False,
                                        n_samples=58188,
                                        random_state=123)

# Combine minority class with Downsampled majority class
df_1_balanced = pd.concat([df_1_majority_downsampled, df_1_minority])

# Showing the unique value counts of the WEATHER
df_1_balanced.SEVERITYCODE.value_counts()

2    58188
1    58188
Name: SEVERITYCODE, dtype: int64

In [26]:
import numpy as np
X = np.asarray(df_1_balanced[['WEATHER_CODE', 'ROADCOND_CODE', 'LIGHTCOND_CODE']])
X[0:5]

array([[ 6,  8,  2],
       [ 1,  0,  5],
       [10,  7,  8],
       [ 1,  0,  5],
       [ 1,  0,  5]], dtype=int8)

In [27]:
y = np.asarray(df_1_balanced['SEVERITYCODE'])
y [0:5]

array([1, 1, 1, 1, 1])

In [28]:
from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X)
X[0:5]

array([[ 1.15236718,  1.52797946, -1.21648407],
       [-0.67488   , -0.67084969,  0.42978835],
       [ 2.61416492,  1.25312582,  2.07606076],
       [-0.67488   , -0.67084969,  0.42978835],
       [-0.67488   , -0.67084969,  0.42978835]])

In [55]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (81463, 3) (81463,)
Test set: (34913, 3) (34913,)

In [68]:
# Building the KNN Model
from sklearn.neighbors import KNeighborsClassifier

k = 25

In [69]:
#Train Model & Predict  
neigh = KNeighborsClassifier(n_neighbors = k).fit(X_train,y_train)
neigh

Kyhat = neigh.predict(X_test)
Kyhat[0:5]

array([2, 2, 1, 1, 2])

In [70]:
# Building the LR Model
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR_model = LogisticRegression(C=6, solver='liblinear').fit(X_train,y_train)
LR_model

LogisticRegression(C=6, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [71]:
# Train Model & Predicr
LRyhat = LR_model.predict(X_test)
LRyhat

array([1, 2, 1, ..., 2, 2, 2])

In [72]:
yhat_prob = LR_model.predict_proba(X_test)
yhat_prob

array([[0.57295252, 0.42704748],
       [0.47065071, 0.52934929],
       [0.67630201, 0.32369799],
       ...,
       [0.46929132, 0.53070868],
       [0.47065071, 0.52934929],
       [0.46929132, 0.53070868]])

In [73]:
from sklearn.metrics import jaccard_similarity_score
from sklearn.metrics import f1_score
from sklearn.metrics import log_loss

In [74]:
# Jaccard Similarity Score
jaccard_similarity_score(y_test, Kyhat)

/Users/chunghimlau/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:635: DeprecationWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  'and multiclass classification tasks.', DeprecationWarning)

0.564001947698565

In [75]:
# F1-SCORE
f1_score(y_test, Kyhat, average='macro')

0.5401775308974308

In [76]:
# Jaccard Similarity Score
jaccard_similarity_score(y_test, LRyhat)

/Users/chunghimlau/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:635: DeprecationWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  'and multiclass classification tasks.', DeprecationWarning)

0.5260218256809784

In [77]:
# F1-SCORE
f1_score(y_test, LRyhat, average='macro')

0.511602093963383

In [79]:
# LOGLOSS
yhat_prob = LR.predict_proba(X_test)
log_loss(y_test, yhat_prob)

0.6849645620904034